Feat/update expiring todo comments
ornikar/eslint-configs pull request #297
Opened 2022-04-25 10:46 UTC by onk-mickael

### Context

Ignorer les dates + autoriser les tickets JIRA [expiring-todo-comments.md](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/expiring-todo-comments.md)

2022-04-25 11:51 UTC, christophehurpeau commented on @ornikar/eslint-config/rules/unicorn.js
> +        ignore: [/[A-Z]-\d+/i], // JIRA issue format (DR-123)
```suggestion
        ignore: [/^\s*https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]-\d+/i], // JIRA issue format (DR-123)
```

plutot un lien ?

2022-04-26 09:22 UTC, christophehurpeau commented on @ornikar/eslint-config/rules/unicorn.js
> +        ignore: [/https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+/i], // JIRA issue format (ex: https://ornikar.atlassian.net/browse/DR-123)
```suggestion
        ignore: [/^https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+$/i], // JIRA issue format (ex: https://ornikar.atlassian.net/browse/DR-123)
```

2022-04-26 09:25 UTC, onk-mickael commented on @ornikar/eslint-config/rules/unicorn.js
> +        ignore: [/https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+/i], // JIRA issue format (ex: https://ornikar.atlassian.net/browse/DR-123)
Cette regex ne semble pas valide :/

2022-04-29 07:58 UTC, christophehurpeau commented on @ornikar/eslint-config/tests/expiring-todo-comments.js
> +// ❌ Incorrect uses with this rule
tu as pas d'exemple avec les dates ? si je comprends bien la config, elles devraient toutes etre invalides ?

2022-04-29 08:00 UTC, christophehurpeau commented on @ornikar/eslint-config/rules/unicorn.js
> +        ignore: [/https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+/i], // JIRA issue format (ex: https://ornikar.atlassian.net/browse/DR-123)
essayes `/^[https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+]/i` ou `/^TODO [https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+/i`

2022-05-02 15:01 UTC, christophehurpeau requested changes

2022-05-02 15:01 UTC, christophehurpeau commented on @ornikar/eslint-config/rules/unicorn.js
> +        date: '2000-01-01', // ignores expiring dates >2000-01-01
je serais plutot pour mettre la date max et obliger a pas passer par une date mais une issue

2022-05-05 14:28 UTC, onk-mickael commented on @ornikar/eslint-config/rules/unicorn.js
> +        ignore: [/https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+/i], // JIRA issue format (ex: https://ornikar.atlassian.net/browse/DR-123)
Celle-ci passe et inclut les brackets `()` étant le groupe de capture: 

`/(\[https:\/\/ornikar.atlassian.net\/browse\/[A-Z]+-\d+])/i`

2022-05-05 14:30 UTC, onk-mickael commented on @ornikar/eslint-config/tests/expiring-todo-comments.js
> +// ❌ Incorrect uses with this rule
C'est ajouté

2022-05-05 19:14 UTC, christophehurpeau commented on @ornikar/eslint-config/rules/unicorn.js
> +        ignore: [/https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+/i], // JIRA issue format (ex: https://ornikar.atlassian.net/browse/DR-123)
l'idée c'est d'avoir ^ au debut et $ a la fin pour pas que ca match `TODO [invalidstart https://ornikar.atlassian.net/browse/DR-123 invalidend]

2022-05-05 19:15 UTC, christophehurpeau commented on @ornikar/eslint-config/rules/unicorn.js
> +        date: '3000-01-01', // invalidates all expiring dates <3000-01-01
```suggestion
        date: '9999-12-31', // invalidates all expiring dates <3000-01-01
```
?

2022-05-06 14:15 UTC, onk-mickael commented on @ornikar/eslint-config/rules/unicorn.js
> +        ignore: [/https:\/\/ornikar\.atlassian\.net\/browse\/[A-Z]+-\d+/i], // JIRA issue format (ex: https://ornikar.atlassian.net/browse/DR-123)
C'est ça cette regex fait exactement ce check ;)

2022-05-06 16:42 UTC, christophehurpeau approved these changes
merci !  (juste l'ajout des deux invalides en plus :))

2022-05-12 09:34 UTC, merged