chore: add es-lint-plugin-tsdoc plugin for nestjs rules [no issue]
ornikar/eslint-configs pull request #403
Opened 2022-09-23 12:17 UTC by sylvaingrasland-ornikar

### Context

We want to check that TSDoc comments are in the right format in our NestJS code.

### Solution

Add `es-lint-plugin-tsdoc` plugin with rule set to _warn_.

2022-09-23 13:10 UTC, christophehurpeau requested changes
rajouter un test :) exemple: https://github.com/ornikar/eslint-configs/commit/dc1b32009fb280fdc886186266e0da8bc905b048#diff-0859d1e54453031b8115e5a43206e828285a9f4edc77c371bba0ca361cc8aa5a

2022-09-23 13:13 UTC, christophehurpeau commented
si c'est un test, peut-etre rajouter dans votre repo avant de mettre en config partagé ?https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2067267674/Code+Quality+Working+Group+Eslint#Clean-config

2022-09-26 08:40 UTC, sylvaingrasland-ornikar commented
> si c'est un test, peut-etre rajouter dans votre repo avant de mettre en config partagé ?https://ornikar.atlassian.net/wiki/spaces/TECH/pages/2067267674/Code+Quality+Working+Group+Eslint#Clean-config

Question transférée ici : https://github.com/ornikar/insurance-backend/pull/1118#discussion_r979725321

2022-09-27 08:06 UTC, sylvaingrasland-ornikar commented
Comme répondu sur https://github.com/ornikar/insurance-backend/pull/1118#discussion_r980900568, on va effectivement commencer par mettre ce plugin dans notre propre repo 👍

2022-09-27 08:06 UTC, closed without merging