feat: add rules for eslint meeting ARCH-1376
ornikar/eslint-configs pull request #50
Opened 2021-06-02 16:28 UTC by ChibiBlasphem

### Context

https://github.com/ornikar/eslint-configs/discussions/23

https://github.com/ornikar/eslint-configs/discussions/28  

### Solution

- Update `typescript-eslint.js` to add rule `@typescript-eslint/no-non-null-assertion` with `error` setting, to a new commented category called “'warn' to ‘error’”
- Update `eslint-configs/@ornikar/eslint-config-react/rules/react.js` to add `react/function-component-definition` rule with proposed code in repository rule discussion

2021-06-02 16:51 UTC, christophehurpeau requested changes

2021-06-02 16:51 UTC, christophehurpeau commented on @ornikar/eslint-config-react/tests/Typography.js
> +}
```suggestion
// eslint-disable-next-line react/function-component-definition
const InvalidFunctionComponent = () => null;
```

c'est le test ! faut le garder :)

tu peux en rajouter un autre pour unnamedComponents ?

2021-06-02 16:51 UTC, christophehurpeau commented on @ornikar/eslint-config-typescript-react/tests/react.tsx
> +  function IntlProvider({ children }: Parameters<FC>[0]): ReturnType<FC> {
pareil ici c'est un test, donc a garder avec un eslint ignore ?

2021-06-02 16:51 UTC, christophehurpeau commented on @ornikar/eslint-config-typescript-react/tests/react.tsx
> +  function IntlProvider({ children }: Parameters<FC>[0]): ReturnType<FC> {
c'est le test pour unnamedComponents  non ?

2021-06-02 16:54 UTC, ChibiBlasphem commented on @ornikar/eslint-config-react/tests/Typography.js
> +}
Ok j'update ça

2021-06-03 07:14 UTC, christophehurpeau approved these changes

2021-06-03 07:54 UTC, merged